In [42]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers
tf.__version__

'2.10.0'

In [43]:
a=1.2
aa=tf.constant(1.2)
type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

In [44]:
x=tf.constant([1, 2., 3.3])
x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

In [45]:
x.numpy()

array([1. , 2. , 3.3], dtype=float32)

In [46]:
a=tf.constant([1.2])
a, a.shape

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

In [47]:
a=tf.constant([1, 2, 3.])
a, a.shape

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 TensorShape([3]))

In [48]:
a=tf.constant([[1,2],[3,4]])
a, a.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 TensorShape([2, 2]))

In [49]:
a=tf.constant([[[1,2],[3,4]], [[5,6],[7,8]]])
a, a.shape

(<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]])>,
 TensorShape([2, 2, 2]))

In [50]:
a=tf.constant('Hello, Deep learning')
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, Deep learning'>

In [51]:
tf.strings.lower(a)

<tf.Tensor: shape=(), dtype=string, numpy=b'hello, deep learning'>

In [52]:
a=tf.constant(True)
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [53]:
a=tf.constant([True, False])
a

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [54]:
a=tf.constant(True)
a is True

False

In [55]:
tf.constant(123456789, dtype=tf.int16)
tf.constant(123456789, dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=123456789>

In [56]:
tf.constant(np.pi, dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=3.1415927>

In [57]:
tf.constant(np.pi, dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=3.141592653589793>

In [58]:
a=tf.constant(np.pi, dtype=tf.float16)
print('before:', a.dtype)
if a.dtype!=tf.float32:
    a=tf.cast(a, tf.float32)
print('after:', a.dtype)

before: <dtype: 'float16'>
after: <dtype: 'float32'>


In [59]:
a=tf.constant(123456789, dtype=tf.int32)
tf.cast(a, tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

In [60]:
a=tf.constant([True, False])
tf.cast(a, tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0])>

In [61]:
a=tf.constant([-1, 0, 1, 2])
tf.cast(a, tf.bool)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

In [62]:
a=tf.constant([-1, 0, 1, 2])
aa=tf.Variable(a)
aa.name, aa.trainable

('Variable:0', True)

In [63]:
a=tf.Variable([[1,2],[3,4]])
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [64]:
# create tensor from python list
tf.convert_to_tensor([1, 2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [65]:
# create a tensor from numpy array
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [66]:
tf.zeros([]), tf.ones([])

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

In [67]:
tf.zeros([1]), tf.ones([1])

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

In [68]:
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [69]:
tf.ones([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [70]:
a=tf.ones([2,3])
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [71]:
a=tf.zeros([3, 2])
tf.zeros_like(a)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [72]:
tf.fill([], -1)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [73]:
tf.fill([1], -1)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([-1])>

In [74]:
tf.fill([2,2], 99)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]])>

In [75]:
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.3198273 , -0.47163063],
       [-0.37961525,  0.21774274]], dtype=float32)>

In [76]:
tf.random.normal([2,2], mean=1, stddev=2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 3.7581997 , -0.61222136],
       [-1.7590346 ,  2.0981197 ]], dtype=float32)>

In [77]:
tf.random.uniform([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.991601  , 0.38334334],
       [0.84415805, 0.24498498]], dtype=float32)>

In [78]:
tf.random.uniform([2,2], maxval=10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8.869516 , 1.7638588],
       [3.924483 , 3.4429276]], dtype=float32)>

In [79]:
tf.random.uniform([2,2], maxval=100, dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 15],
       [76,  3]])>

In [80]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [81]:
tf.range(10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

In [82]:
tf.range(1, 10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>