In [14]:
import tensorflow as tf

In [15]:
x = tf.range(96)

In [16]:
x

<tf.Tensor: shape=(96,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95])>

In [17]:
x = tf.reshape(x,[2,4,4,3])

In [18]:
x

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]])>

In [21]:
x= tf.reshape(x,[2,-1])
x

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])>

In [20]:
x=tf.reshape(x,[2,4,12])
x

<tf.Tensor: shape=(2, 4, 12), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]])>

In [22]:
x=tf.reshape(x,[2,-1,16])
x

<tf.Tensor: shape=(2, 3, 16), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
        [64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]])>

In [23]:
add = tf.random.uniform([28,28],maxval=10,dtype=tf.int32)
add

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[2, 7, 7, 5, 6, 7, 8, 3, 0, 3, 8, 7, 1, 7, 6, 8, 6, 7, 2, 2, 7, 1,
        5, 0, 8, 0, 2, 8],
       [4, 8, 4, 0, 0, 6, 7, 2, 3, 9, 6, 1, 4, 8, 0, 4, 7, 4, 2, 8, 5, 2,
        9, 7, 2, 8, 2, 6],
       [5, 3, 0, 8, 9, 8, 8, 8, 9, 5, 6, 5, 0, 3, 5, 0, 9, 1, 4, 8, 3, 4,
        8, 7, 1, 9, 2, 0],
       [6, 2, 2, 3, 8, 8, 1, 0, 6, 7, 8, 1, 0, 9, 0, 0, 3, 6, 4, 7, 7, 8,
        2, 3, 4, 3, 6, 2],
       [4, 2, 1, 4, 2, 5, 4, 0, 6, 1, 6, 7, 3, 0, 9, 3, 6, 1, 2, 6, 1, 1,
        4, 5, 7, 2, 4, 7],
       [0, 2, 9, 2, 3, 8, 3, 3, 1, 8, 2, 8, 0, 6, 5, 3, 5, 7, 1, 5, 4, 2,
        5, 3, 1, 4, 5, 3],
       [8, 9, 6, 7, 3, 6, 7, 9, 3, 5, 7, 8, 4, 7, 4, 7, 6, 3, 0, 4, 0, 5,
        9, 5, 4, 4, 6, 8],
       [5, 0, 5, 3, 1, 2, 7, 3, 4, 2, 9, 0, 9, 6, 5, 4, 1, 6, 0, 1, 1, 6,
        1, 4, 3, 6, 1, 5],
       [3, 9, 1, 5, 8, 6, 2, 0, 8, 9, 5, 0, 0, 6, 6, 0, 4, 4, 6, 4, 1, 5,
        5, 4, 4, 1, 7, 1],
       [8, 5, 2, 8, 6, 7, 9, 6, 0, 7, 3, 9,

In [24]:
add= tf.expand_dims(add,axis=1)
add

<tf.Tensor: shape=(28, 1, 28), dtype=int32, numpy=
array([[[2, 7, 7, 5, 6, 7, 8, 3, 0, 3, 8, 7, 1, 7, 6, 8, 6, 7, 2, 2, 7,
         1, 5, 0, 8, 0, 2, 8]],

       [[4, 8, 4, 0, 0, 6, 7, 2, 3, 9, 6, 1, 4, 8, 0, 4, 7, 4, 2, 8, 5,
         2, 9, 7, 2, 8, 2, 6]],

       [[5, 3, 0, 8, 9, 8, 8, 8, 9, 5, 6, 5, 0, 3, 5, 0, 9, 1, 4, 8, 3,
         4, 8, 7, 1, 9, 2, 0]],

       [[6, 2, 2, 3, 8, 8, 1, 0, 6, 7, 8, 1, 0, 9, 0, 0, 3, 6, 4, 7, 7,
         8, 2, 3, 4, 3, 6, 2]],

       [[4, 2, 1, 4, 2, 5, 4, 0, 6, 1, 6, 7, 3, 0, 9, 3, 6, 1, 2, 6, 1,
         1, 4, 5, 7, 2, 4, 7]],

       [[0, 2, 9, 2, 3, 8, 3, 3, 1, 8, 2, 8, 0, 6, 5, 3, 5, 7, 1, 5, 4,
         2, 5, 3, 1, 4, 5, 3]],

       [[8, 9, 6, 7, 3, 6, 7, 9, 3, 5, 7, 8, 4, 7, 4, 7, 6, 3, 0, 4, 0,
         5, 9, 5, 4, 4, 6, 8]],

       [[5, 0, 5, 3, 1, 2, 7, 3, 4, 2, 9, 0, 9, 6, 5, 4, 1, 6, 0, 1, 1,
         6, 1, 4, 3, 6, 1, 5]],

       [[3, 9, 1, 5, 8, 6, 2, 0, 8, 9, 5, 0, 0, 6, 6, 0, 4, 4, 6, 4, 1,
         5, 5, 4, 4, 1, 7, 1]],

    