In [1]:
import tensorflow as tf

In [2]:
x = tf.random.normal([2,784])

In [3]:
w1 = tf.Variable(tf.random.truncated_normal([784, 256],stddev=0.1))

In [4]:
b1 = tf.Variable(tf.zeros([256]))

In [5]:
o1 = tf.matmul(x,w1) + b1
o1

<tf.Tensor: shape=(2, 256), dtype=float32, numpy=
array([[-3.47710323e+00, -3.88996410e+00,  2.76872778e+00,
        -1.53406549e+00,  3.18171740e-01,  3.17707205e+00,
        -3.46102285e+00, -1.45592165e+00, -1.38516378e+00,
         3.60437536e+00,  6.88840806e-01,  2.04236937e+00,
         5.03951263e+00, -1.84358168e+00, -4.20247221e+00,
        -2.15905428e-01, -2.43505383e+00, -4.28357697e+00,
         3.13733244e+00, -1.60089278e+00, -7.67074728e+00,
         6.69232130e-01, -1.66768587e+00, -1.40745997e+00,
        -1.59356475e+00,  3.22094083e-01, -6.70279264e-01,
         8.61823678e-01, -3.19578075e+00, -2.22126818e+00,
         1.24419165e+00,  2.69526076e+00, -6.64605045e+00,
        -5.22222090e+00,  1.21525168e+00,  7.81253576e-01,
         4.48333216e+00,  5.38372993e-03,  1.20490551e+00,
        -1.25568748e+00, -9.42469835e-01,  3.11158729e+00,
         4.82548857e+00, -1.82402682e+00, -1.81097448e-01,
         9.20256436e-01,  1.12992692e+00, -4.47458029e-01,
      

In [6]:
o1 = tf.nn.relu(o1) 
o1

<tf.Tensor: shape=(2, 256), dtype=float32, numpy=
array([[0.00000000e+00, 0.00000000e+00, 2.76872778e+00, 0.00000000e+00,
        3.18171740e-01, 3.17707205e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.60437536e+00, 6.88840806e-01, 2.04236937e+00,
        5.03951263e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 3.13733244e+00, 0.00000000e+00,
        0.00000000e+00, 6.69232130e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.22094083e-01, 0.00000000e+00, 8.61823678e-01,
        0.00000000e+00, 0.00000000e+00, 1.24419165e+00, 2.69526076e+00,
        0.00000000e+00, 0.00000000e+00, 1.21525168e+00, 7.81253576e-01,
        4.48333216e+00, 5.38372993e-03, 1.20490551e+00, 0.00000000e+00,
        0.00000000e+00, 3.11158729e+00, 4.82548857e+00, 0.00000000e+00,
        0.00000000e+00, 9.20256436e-01, 1.12992692e+00, 0.00000000e+00,
        3.34500718e+00, 0.00000000e+00, 4.60889006e+00, 2.28641582e+00,
        0.0000