In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([1,2,3,4,5,6])
b = tf.constant([7,8,1,6])
b = tf.pad(b, [[0,2]])
b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([7, 8, 1, 6, 0, 0])>

In [3]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6],
       [7, 8, 1, 6, 0, 0]])>

In [4]:
x = tf.random.normal([4,28,28,1])
x

<tf.Tensor: shape=(4, 28, 28, 1), dtype=float32, numpy=
array([[[[ 1.8852367e+00],
         [-2.0377307e-01],
         [-7.2700542e-01],
         ...,
         [-1.3626094e-01],
         [-7.2415096e-01],
         [-7.0110196e-01]],

        [[ 1.2701166e+00],
         [-1.2664604e-01],
         [-2.2902899e+00],
         ...,
         [-1.0816982e+00],
         [-5.6250566e-01],
         [ 7.8305535e-02]],

        [[-1.6736667e-01],
         [-5.0712235e-02],
         [-1.4227641e-01],
         ...,
         [ 1.2887992e+00],
         [ 1.4972737e+00],
         [ 3.4130249e-02]],

        ...,

        [[-4.6737498e-01],
         [ 1.9833555e+00],
         [ 1.0473864e+00],
         ...,
         [ 3.9952269e-01],
         [-3.4252876e-01],
         [ 7.7465810e-02]],

        [[ 1.5356756e+00],
         [-2.3634924e-01],
         [ 1.4984800e+00],
         ...,
         [-6.8749571e-01],
         [-1.0744312e-01],
         [-2.5792155e+00]],

        [[-3.5551567e-02],
         [ 9.

In [5]:
tf.pad(x,[[0,0],[2,2],[2,2],[0,0]])

<tf.Tensor: shape=(4, 32, 32, 1), dtype=float32, numpy=
array([[[[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 1.8852367 ],
         ...,
         [-0.70110196],
         [ 0.        ],
         [ 0.        ]],

        ...,

        [[ 0.        ],
         [ 0.        ],
         [-0.03555157],
         ...,
         [-0.18839122],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.       

In [6]:
x = tf.random.normal([4,32,32,3])
tf.tile(x,[2,3,3,1])

<tf.Tensor: shape=(8, 96, 96, 3), dtype=float32, numpy=
array([[[[-0.34604988, -0.53745   ,  1.03845   ],
         [-1.0991689 , -0.37422374,  0.12572628],
         [ 0.7788735 , -1.6352935 , -0.5422237 ],
         ...,
         [-0.9421661 ,  0.9447926 , -1.1321108 ],
         [ 1.0561545 , -0.4724724 ,  0.92861396],
         [-0.06295045, -0.02878363,  1.3036615 ]],

        [[ 1.6601026 ,  0.24679811, -0.24667826],
         [ 0.62884724, -0.55034107,  1.4511179 ],
         [-0.08302499,  1.4157346 , -0.38831598],
         ...,
         [-0.46880555, -1.035315  ,  0.08340574],
         [ 1.5079597 ,  1.9304527 ,  1.3672105 ],
         [-0.8804691 , -0.7245555 ,  0.60175025]],

        [[ 0.0582606 ,  0.07308281,  1.192113  ],
         [ 0.20609619,  0.73004764,  0.08390583],
         [ 1.2658155 , -0.19482487, -0.16990578],
         ...,
         [-1.638758  ,  1.4938225 , -0.9282539 ],
         [-0.5757242 , -0.33503145, -1.2607353 ],
         [ 0.4462035 , -0.99537665,  1.226676  ]