In [12]:
import tensorflow as tf

In [13]:
a = tf.constant([1,2,3,4,5,6])
b = tf.constant([7,8,1,6])
b = tf.pad(b, [[0,2]])
b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([7, 8, 1, 6, 0, 0])>

In [14]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6],
       [7, 8, 1, 6, 0, 0]])>

In [15]:
x = tf.random.normal([4,28,28,1])
x

<tf.Tensor: shape=(4, 28, 28, 1), dtype=float32, numpy=
array([[[[ 1.6155005e+00],
         [-1.6453993e+00],
         [-2.3682427e+00],
         ...,
         [-5.7563555e-01],
         [-1.4282275e+00],
         [ 1.0568071e-01]],

        [[-1.2943095e-01],
         [ 9.1631371e-01],
         [-9.2284811e-01],
         ...,
         [ 1.1465716e+00],
         [-1.3130260e+00],
         [ 3.7674445e-01]],

        [[-1.0129962e+00],
         [ 5.2008855e-01],
         [-4.7016966e-01],
         ...,
         [ 2.2268032e-04],
         [ 2.1415426e-01],
         [-1.4965433e+00]],

        ...,

        [[ 8.8910055e-01],
         [-1.4936949e+00],
         [ 1.1693542e+00],
         ...,
         [-2.0024517e+00],
         [ 6.6973776e-01],
         [-2.3229943e-01]],

        [[ 1.3447762e+00],
         [-1.5159987e-01],
         [-5.9098810e-01],
         ...,
         [ 2.9064507e+00],
         [ 1.4983097e+00],
         [-4.1899577e-01]],

        [[-6.6873327e-02],
         [ 6.

In [17]:
tf.pad(x,[[0,0],[2,2],[2,2],[0,0]])

<tf.Tensor: shape=(4, 32, 32, 1), dtype=float32, numpy=
array([[[[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 1.6155005 ],
         ...,
         [ 0.10568071],
         [ 0.        ],
         [ 0.        ]],

        ...,

        [[ 0.        ],
         [ 0.        ],
         [-0.06687333],
         ...,
         [-0.14676371],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.       

In [18]:
x = tf.random.normal([4,32,32,3])
tf.tile(x,[2,3,3,1])

<tf.Tensor: shape=(8, 96, 96, 3), dtype=float32, numpy=
array([[[[ 9.81914550e-02, -1.29248166e+00, -2.01289162e-01],
         [-2.89540708e-01,  1.02690244e+00,  2.12897256e-01],
         [-2.13536096e+00, -8.88034880e-01,  6.55609846e-01],
         ...,
         [ 7.55929351e-01,  6.15010738e-01, -1.06245792e+00],
         [ 5.43003738e-01,  1.09393072e+00,  4.22078311e-01],
         [-6.27651930e-01,  5.46540558e-01, -3.27222764e-01]],

        [[-2.23818555e-01, -1.43279925e-01,  1.77388060e+00],
         [ 7.36429989e-01, -1.56532884e-01,  2.13055182e+00],
         [-1.93353021e+00, -9.56301928e-01, -1.68730474e+00],
         ...,
         [ 2.19192791e+00,  8.14572036e-01, -6.17552876e-01],
         [-7.72642493e-02,  1.00882560e-01, -7.98573375e-01],
         [-4.65895981e-01, -1.50229359e+00,  9.48293209e-01]],

        [[-1.55289066e+00,  5.01320814e-04, -9.50908005e-01],
         [-5.74172676e-01,  9.65489149e-01, -7.17120886e-01],
         [ 7.90848136e-01, -1.15160555e-01, 