In [1]:
import tensorflow as tf

In [2]:
out = tf.random.normal([10,10])

In [3]:
out

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[-0.01597639,  1.3664459 , -1.6160903 , -0.34370026,  1.0377682 ,
        -0.2266074 ,  0.02064795,  1.1520959 ,  0.10231864, -0.04111759],
       [ 0.17452724,  0.3887003 ,  0.1191181 ,  0.885783  , -1.4503514 ,
         1.2521029 ,  0.57200694, -0.30865148, -0.40633073,  0.02463236],
       [-1.1530709 ,  0.06415338, -0.03132118,  1.3785287 ,  0.555266  ,
        -0.62659574,  0.02659829,  0.34762752, -0.7253514 ,  0.3413014 ],
       [ 0.9129736 , -0.8206592 ,  0.01474554, -0.17788167,  0.10352934,
         1.2443781 ,  0.93194896,  1.240582  , -1.9567071 ,  0.03125641],
       [ 0.63244426,  0.30570942, -0.812482  , -0.3971484 ,  0.8117377 ,
         0.18702915,  1.9385656 , -1.5532045 ,  1.3225857 ,  0.29572007],
       [ 0.31282172, -1.1167876 ,  1.6380948 , -2.043683  ,  0.4322391 ,
         0.2956094 ,  0.3537698 ,  2.3451278 ,  0.2002587 , -0.6262249 ],
       [ 0.4837452 , -1.2385434 , -0.75873727, -1.136308  , -0.19617

In [4]:
out = tf.nn.softmax(out,axis=1)

In [5]:
out

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.06273816, 0.2499828 , 0.01266517, 0.04520673, 0.17995638,
        0.05082248, 0.0650785 , 0.2017526 , 0.07061657, 0.06118051],
       [0.08416749, 0.1042698 , 0.07963068, 0.17141104, 0.01657557,
        0.24724612, 0.12524708, 0.05191615, 0.04708482, 0.07245123],
       [0.02441242, 0.08246023, 0.07495152, 0.306952  , 0.134751  ,
        0.0413291 , 0.07942086, 0.10948529, 0.03744268, 0.10879486],
       [0.150705  , 0.02662076, 0.06138075, 0.05062619, 0.0670796 ,
        0.20992048, 0.15359199, 0.20912512, 0.00854754, 0.06240261],
       [0.09377824, 0.0676399 , 0.02210948, 0.03349312, 0.11219362,
        0.06007043, 0.34621298, 0.01054112, 0.18699357, 0.06696758],
       [0.05825758, 0.01394701, 0.21923569, 0.00551995, 0.06564698,
        0.05726342, 0.06069263, 0.4446024 , 0.05205555, 0.02277874],
       [0.16776025, 0.02997151, 0.04842681, 0.03319777, 0.08499687,
        0.08891798, 0.10838219, 0.28894398, 0.05275296, 0.09

In [6]:
pred = tf.argmax(out,axis=1)

In [7]:
pred

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 5, 3, 5, 6, 7, 7, 1, 1, 1], dtype=int64)>

In [8]:
#stimulate the true values
t=tf.random.uniform([10],dtype=tf.int64,maxval=10)

In [9]:
t

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([5, 5, 0, 2, 0, 3, 9, 0, 1, 6], dtype=int64)>

In [10]:
out = tf.equal(pred,t)

In [11]:
out

<tf.Tensor: shape=(10,), dtype=bool, numpy=
array([False,  True, False, False, False, False, False, False,  True,
       False])>

In [12]:
out =tf.math.greater(pred,t)#greater

In [13]:
out

<tf.Tensor: shape=(10,), dtype=bool, numpy=
array([False, False,  True,  True,  True,  True, False,  True, False,
       False])>