In [1]:
import tensorflow as tf

In [2]:
out = tf.random.normal([10,10])

In [3]:
out

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[ 1.0556035 , -1.5369633 , -0.12314512,  2.0703313 , -0.82220924,
         0.38238478, -0.7237324 , -0.96389455,  0.3249465 , -0.5990914 ],
       [-0.82418674,  0.18389426, -2.112837  ,  0.7129274 , -2.1593423 ,
        -0.6031562 , -0.76204735, -1.2756188 , -2.7180648 ,  0.44344148],
       [ 0.6624468 ,  2.1776805 ,  0.8931816 , -0.5183056 ,  0.06475206,
         0.57676214,  1.377201  , -0.23611915, -0.38549107, -0.3142977 ],
       [ 0.66293895, -0.9087488 , -0.6271027 , -0.16027912, -0.806617  ,
        -0.48899636, -0.1889427 ,  1.5090492 , -0.2201459 , -0.6988514 ],
       [ 0.38352752,  0.3732753 , -0.53802073,  0.7745084 ,  0.44551352,
        -0.37486553,  0.4353031 ,  1.7791749 , -0.35623375, -0.03819746],
       [-0.10887493, -1.550203  ,  0.3273064 , -0.5385988 , -0.1902615 ,
        -1.0994475 ,  0.48238868, -0.6526342 ,  0.37708607, -0.10834747],
       [ 0.18108338,  0.532856  ,  1.3552439 ,  0.8540276 ,  0.07467

In [4]:
out = tf.nn.softmax(out,axis=1)

In [5]:
out

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.17306107, 0.01294977, 0.05324457, 0.4774084 , 0.02646523,
        0.08827224, 0.02920408, 0.02296902, 0.08334491, 0.03308069],
       [0.06417934, 0.17587303, 0.01769056, 0.29850763, 0.01688669,
        0.08005483, 0.06829392, 0.04086399, 0.00965816, 0.22799177],
       [0.08501195, 0.3868456 , 0.1070747 , 0.02610272, 0.04676323,
        0.07803109, 0.1737376 , 0.03461288, 0.0298103 , 0.03200997],
       [0.16963804, 0.03523286, 0.04669445, 0.07447391, 0.03902143,
        0.05360978, 0.07236953, 0.39535227, 0.07014623, 0.04346155],
       [0.086041  , 0.08516338, 0.03423593, 0.1272056 , 0.09154309,
        0.0403032 , 0.09061315, 0.34739804, 0.04106116, 0.05643552],
       [0.10266533, 0.02429198, 0.15880162, 0.06680316, 0.09464071,
        0.0381262 , 0.18544123, 0.05960355, 0.16690677, 0.10271949],
       [0.03028843, 0.04305758, 0.09799596, 0.05936531, 0.02723092,
        0.07446674, 0.04973137, 0.00634691, 0.10692536, 0.50

In [6]:
pred = tf.argmax(out,axis=1)

In [7]:
pred

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([3, 3, 1, 7, 7, 6, 9, 3, 3, 8], dtype=int64)>

In [8]:
#stimulate the true values
t=tf.random.uniform([10],dtype=tf.int64,maxval=10)

In [9]:
t

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([3, 0, 7, 8, 0, 5, 6, 4, 9, 6], dtype=int64)>

In [10]:
out = tf.equal(pred,t)

In [11]:
out

<tf.Tensor: shape=(10,), dtype=bool, numpy=
array([ True, False, False, False, False, False, False, False, False,
       False])>

In [12]:
out =tf.math.greater(pred,t)#greater

In [13]:
out

<tf.Tensor: shape=(10,), dtype=bool, numpy=
array([False,  True, False, False,  True,  True,  True, False, False,
        True])>