In [1]:
import tensorflow as tf

In [2]:
out = tf.random.normal([10,10])

In [3]:
out

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[ 0.19929945,  0.9361519 , -0.2362317 , -1.0283223 , -0.9298985 ,
         1.085041  , -0.36366472, -0.26736924, -0.25325015,  1.087245  ],
       [-0.9688182 , -0.11385972,  0.24780814,  0.44068086, -0.4133442 ,
        -0.42571917,  0.86462224,  0.0339622 , -0.73208416,  1.0295212 ],
       [ 0.0861766 , -1.6684247 , -0.6324727 , -0.86904013,  0.19711252,
        -0.5303762 ,  1.1428748 ,  0.2193477 , -1.1258417 ,  1.061597  ],
       [-1.0325513 ,  0.57039165, -0.7605583 ,  0.7927843 , -0.12288146,
         0.8035709 ,  0.9203224 ,  0.04742539, -0.18319395, -0.83878696],
       [ 1.7866217 , -1.005533  , -1.30395   , -0.01141103,  0.06236   ,
         0.37483183, -1.2921824 ,  0.11333071,  0.36988765,  0.05057006],
       [ 0.31877333,  0.86975837,  1.6315824 , -2.1294231 , -1.443429  ,
        -1.7830676 ,  0.79917413, -1.1013936 , -0.82772994, -0.34650335],
       [-0.7530053 ,  0.11318658,  0.28096667, -1.3423237 , -0.26709

In [4]:
out = tf.nn.softmax(out,axis=1)

In [5]:
out

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.09057909, 0.18925132, 0.05859751, 0.02653864, 0.02928354,
        0.21963455, 0.05158646, 0.05680104, 0.05760871, 0.22011913],
       [0.03133796, 0.07368421, 0.10579005, 0.1282946 , 0.05461476,
        0.05394307, 0.19603056, 0.08542258, 0.03970846, 0.23117374],
       [0.09370824, 0.0162093 , 0.04567435, 0.03605225, 0.1047024 ,
        0.0505839 , 0.26958516, 0.10705655, 0.0278872 , 0.24854068],
       [0.0279437 , 0.13881397, 0.03667828, 0.17338721, 0.06939825,
        0.1752676 , 0.19697277, 0.08228333, 0.06533639, 0.03391835],
       [0.42611885, 0.0261164 , 0.01937816, 0.07057568, 0.07597897,
        0.10384801, 0.01960754, 0.07995207, 0.10333584, 0.07508844],
       [0.10501797, 0.18220209, 0.39030966, 0.00907874, 0.01802805,
        0.01283647, 0.16978487, 0.02538007, 0.03336902, 0.05399301],
       [0.04393563, 0.10447183, 0.12355637, 0.02437133, 0.07142416,
        0.0395247 , 0.27413836, 0.11947118, 0.12815093, 0.07

In [6]:
pred = tf.argmax(out,axis=1)

In [7]:
pred

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([9, 9, 6, 6, 0, 2, 6, 5, 5, 9], dtype=int64)>

In [8]:
#stimulate the true values
t=tf.random.uniform([10],dtype=tf.int64,maxval=10)

In [9]:
t

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([4, 5, 8, 6, 9, 3, 5, 8, 3, 5], dtype=int64)>

In [10]:
out = tf.equal(pred,t)

In [11]:
out

<tf.Tensor: shape=(10,), dtype=bool, numpy=
array([False, False, False,  True, False, False, False, False, False,
       False])>

In [12]:
out =tf.math.greater(pred,t)#greater

In [13]:
out

<tf.Tensor: shape=(10,), dtype=bool, numpy=
array([ True,  True, False, False, False, False,  True, False,  True,
        True])>